import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface MonthlyReportData {
  farmName: string;
  month: string;
  year: number;
  production: {
    totalLiters: number;
    avgDaily: number;
    daysRecorded: number;
  };
  deliveries: {
    totalDeliveries: number;
    totalLiters: number;
    customersServed: number;
  };
  payments: {
    totalReceived: number;
    transactionCount: number;
  };
  topCustomers: Array<{
    name: string;
    quantity: number;
    amount: number;
  }>;
  dailyProduction: Array<{
    date: string;
    morning: number;
    evening: number;
    total: number;
  }>;
}

export function generateMonthlyReport(data: MonthlyReportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(34, 87, 59); // Primary green
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("DairyFlow", 20, 25);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Monthly Report - ${data.month} ${data.year}`, pageWidth - 20, 25, { align: "right" });
  
  // Farm name
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(data.farmName || "My Dairy Farm", 20, 55);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-IN", { 
    day: "numeric", 
    month: "long", 
    year: "numeric" 
  })}`, 20, 62);
  
  // Summary Cards
  const cardY = 75;
  const cardWidth = 55;
  const cardGap = 6;
  
  // Production Card
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(20, cardY, cardWidth, 35, 3, 3, "F");
  doc.setTextColor(34, 87, 59);
  doc.setFontSize(9);
  doc.text("Total Production", 25, cardY + 10);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`${data.production.totalLiters}L`, 25, cardY + 25);
  
  // Deliveries Card
  doc.setFillColor(254, 249, 231);
  doc.roundedRect(20 + cardWidth + cardGap, cardY, cardWidth, 35, 3, 3, "F");
  doc.setTextColor(180, 83, 9);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Total Deliveries", 25 + cardWidth + cardGap, cardY + 10);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`${data.deliveries.totalDeliveries}`, 25 + cardWidth + cardGap, cardY + 25);
  
  // Revenue Card
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(20 + (cardWidth + cardGap) * 2, cardY, cardWidth, 35, 3, 3, "F");
  doc.setTextColor(29, 78, 216);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Revenue Collected", 25 + (cardWidth + cardGap) * 2, cardY + 10);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`₹${data.payments.totalReceived.toLocaleString()}`, 25 + (cardWidth + cardGap) * 2, cardY + 25);
  
  // Production Table
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Daily Production Summary", 20, 125);
  
  autoTable(doc, {
    startY: 130,
    head: [["Date", "Morning (L)", "Evening (L)", "Total (L)"]],
    body: data.dailyProduction.slice(0, 15).map(row => [
      new Date(row.date).toLocaleDateString("en-IN", { day: "2-digit", month: "short" }),
      row.morning.toString(),
      row.evening.toString(),
      row.total.toString(),
    ]),
    theme: "striped",
    headStyles: { fillColor: [34, 87, 59] },
    styles: { fontSize: 9 },
    margin: { left: 20, right: 20 },
  });
  
  // Top Customers
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  
  if (finalY < 220) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Top Customers", 20, finalY);
    
    autoTable(doc, {
      startY: finalY + 5,
      head: [["Customer", "Quantity (L)", "Amount (₹)"]],
      body: data.topCustomers.slice(0, 5).map(row => [
        row.name,
        row.quantity.toString(),
        `₹${row.amount.toLocaleString()}`,
      ]),
      theme: "striped",
      headStyles: { fillColor: [180, 83, 9] },
      styles: { fontSize: 9 },
      margin: { left: 20, right: 20 },
    });
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFillColor(245, 245, 245);
  doc.rect(0, pageHeight - 20, pageWidth, 20, "F");
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by DairyFlow - Farm Management System", pageWidth / 2, pageHeight - 10, { align: "center" });
  
  // Save
  doc.save(`DairyFlow_Report_${data.month}_${data.year}.pdf`);
}
